### PR TITLE
Added stl files

### PR DESCRIPTION
**Pull request by NMyren**
Added the stl files for the servo mount.

### CODE REVIEW

**Comment by krishmasand** [comment]
pls explain

Krish

**Comment by NMyren** [comment]
I added the stl files for the mount.

**Comment by JParisFerrer** [comment]
@krishmasand you read my mind

**Comment by krishmasand** [comment]
it's what CAs do

**Comment by Charlie-Lima-Bean** [comment]
STL are the 3D modelling files that are used to 3D print the model

**Comment by NMyren** [comment]
correct

**Comment by Charlie-Lima-Bean** [comment]
It's a good idea to have them to show that they exist and that we made them

**Comment by Charlie-Lima-Bean** [comment]
@channel

**Comment by JParisFerrer** [comment]
This isn't slack, put your @channel's away. (protip you should check who suggested to upload these ;))

**Comment by JParisFerrer** [comment]
Its more obvious if nate hadn't edited the original text lol ("pretty self explanatory ")

**Comment by Charlie-Lima-Bean** [comment]
I was wondering if the @channel would get highlighted in the slack-integrated feed

**Comment by Charlie-Lima-Bean** [comment]
#26 
@JParisFerrer 
see git does these things too

**Comment by JParisFerrer** [comment]
Put your rationalizations away

**Comment by Charlie-Lima-Bean** [comment]
no u

**Comment by JParisFerrer** [comment]
Fite me rite now

**Comment by JParisFerrer** [comment]
In a big O championship

**Comment by Charlie-Lima-Bean** [comment]
irl brah 

at your row or mine
maybe the stairs inbetween

**Comment by JParisFerrer** [comment]
Front of the room

**Comment by JParisFerrer** [comment]
Right behind Chapman

**Comment by Charlie-Lima-Bean** [comment]
aight let's just try not to block the projector

**Pull request merged**
