### PR TITLE
Merging in work that makes the thing actually work.

### PR DESCRIPTION
**Pull request by JParisFerrer**
There is probably some stuff wrong in a certain non-existent file.

### CODE REVIEW

**Comment by NMyren** [comment]
any particular reason for the address change, or is that arbitrary?

**Comment by JParisFerrer** [comment]
? What do you mean?

**Comment by NMyren** [comment]
in the added space commit, you say "addr = "acfdce5ae1b8""

**Comment by JParisFerrer** [comment]
Crap I see what you mean. Used the wrong UUID. no idea what that is for (addr) that's why its probably wrong

**Comment by NMyren** [comment]
what is our UUID?

**Comment by JParisFerrer** [comment]
its the in the ekey file. about to reupload pr. That addr is my pc's bluetooth address, not sure if that's what its looking for tho

**Comment by NMyren** [comment]
ah, I see.

**Comment by NMyren** [comment]
so that'll need to be changed for the pi then?

**Comment by JParisFerrer** [comment]
Well depends on stuff. Probably. Its not meant to be used as you may have guessed.

**Comment by NMyren** [comment]
well, we'll figure it out.

**Comment by NMyren** [comment]
everything else looks good though.

**Pull request closed without merging**
