### PR TITLE
Flask skeleton

### PR DESCRIPTION
**Pull request by Charlie-Lima-Bean**
once again, no libraries on windows sooo sort of untested as usual

Is new file because is really a fork from the original (we will probably
never use web and bluetooth at same time!) . Also this allows us to use
a cleaner (easier to debug) run() without permanently deleting/mucking with all the working
bluetooth/database code

keeping the servo/db functions consistent across both files will be tedious though. maybe we could library those out?

### CODE REVIEW

**Comment by JParisFerrer** [comment]
Shouldn't those def's have () ?

**Comment by Charlie-Lima-Bean** [comment]
Probably,yes

**Comment by Charlie-Lima-Bean** [comment]
Ooh neat my new commit gets added to this pr

**Comment by NMyren** [comment]
looks fine to me. Haven't gotten flask working on my pc yet, so I'm assuming you know what you're doing.

**Comment by JParisFerrer** [comment]
return 'you sent %s!' encryptedstring 

should be

return 'you sent %s!' % encryptedstring

line 37

**Comment by JParisFerrer** [comment]
Ye someone should probably merge this in lol

**Pull request merged**
