### PR TITLE
Added timestamps

### PR DESCRIPTION
**Pull request by JParisFerrer**

### CODE REVIEW

**Comment by Charlie-Lima-Bean** [comment]
I see issues with the highly complex changes made

**Comment by JParisFerrer** [comment]
fixed one such needle in the haystack

**Comment by JParisFerrer** [comment]
Very important yet inconspicuous change added

**Comment by Charlie-Lima-Bean** [comment]
Uh yeah, looks good.

**Comment by JParisFerrer** [comment]
weak merge game team

**Pull request merged**
