### PR TITLE
Crypto Stuff

### PR DESCRIPTION
**Pull request by JParisFerrer**
http://stuvel.eu/rsa

Expects a key file to already exist

Assumes length of data < key length

### CODE REVIEW

**Comment by NMyren** [comment]
What does this do?-
with open("ekey.pem") as pFile:
    keyData = pFile.read()

**Comment by NMyren** [comment]
as a matter of fact, what's a .pem?

**Comment by JParisFerrer** [comment]
Reads the data from the file

Jordi Paris Ferrer

**Comment by JParisFerrer** [comment]
Type of file, we can change that I'm pretty sure

**Comment by NMyren** [comment]
k. Looks fine

**Comment by Charlie-Lima-Bean** [comment]
looks good

**Pull request merged**
