### PR TITLE
Added Libraries folder with rpi.gpio tarball

### PR DESCRIPTION
**Pull request by Charlie-Lima-Bean**
rpi.gpio is the favorite for handling pwm functions. The tarball is a compressed version of the library, so we will have to extract it somewhere where the on-board system can find it once we have our file structure finalized.

### CODE REVIEW

**Comment by JParisFerrer** [comment]
Can we not install it through apt-get or similar? If so then we don't need to copy it in, and we'll just add it to a text file or something (that someone should make with all the packages we need to install separately). For example I'd add pybluez, pybluez[ble], and sqlite3 to the list (assuming python3 is already installed) rather than copy all their sources in.

**Comment by Charlie-Lima-Bean** [comment]
Well ideally we'd have an image prepped so that we can just flash a card and slot it in, so they are easy to mass produce, though we would probably produce that image with some apt-get beforehand and then some sort of boot-up script. This is really just here so it looks like I'm totally doing something.

**Comment by NMyren** [comment]
Hey, you're doing more than me.

**Comment by JParisFerrer** [comment]
As long as someone keeps track of updates, sure. merge it in

**Pull request merged**
