### PR TITLE
logo updates

### PR DESCRIPTION
**Pull request by Charlie-Lima-Bean**
dar be some graphical updates here. Have not checked with compiler, I'm sure it works fine though.

### CODE REVIEW

**Comment by NMyren** [comment]
yep. TY.

**Comment by Charlie-Lima-Bean** [comment]
added hex icon files commit goes into more detail. it's worth the read i swear

**Comment by Charlie-Lima-Bean** [comment]
no it's not

**Comment by JParisFerrer** [comment]
Its truly beautiful

**Comment by Charlie-Lima-Bean** [comment]
bob ross would be proud, I know

**Pull request merged**
