### PR TITLE
Fixes discovered in today's epic battle with raspbian and bluetooth

### PR DESCRIPTION
**Pull request by JParisFerrer**
it was a good fight, but they were no match for 2 hours and a half of intense google-fu

### CODE REVIEW

**Comment by NMyren** [comment]
So where's the magic fix you found?

**Comment by JParisFerrer** [comment]
Its not in the code its on the Pi's OS

**Comment by NMyren** [comment]
oh. Did you have to install some new package?

**Comment by JParisFerrer** [comment]
No it involves editing the actual bluetooth service

**Comment by NMyren** [comment]
jeez. You'll have to explain it to me whenever we meet next. Anyhoo, looks great!

**Pull request merged**
